# Set to the URL for your site
baseURL = "https://hzzhughes.github.io"

# The name of this wonderful theme ;-).
theme = 'hugo-bearblog'

# Basic metadata configuration for your blog.
# title = "Hugo ʕ•ᴥ•ʔ Bear Blog"
author = "Hanbin Zhou"
copyright = "Copyright © 2026, Hanbin Zhou."
languageCode = "en-US"
[params]
hideMadeWithLine = true

[markup.goldmark.renderer]
unsafe = true
